services:
  postgres:
    container_name: sa-agenda
    image: postgres
    volumes:
      - sa-agenda-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  sa-agenda-postgres-data:
    name: sa-agenda-postgres-data